steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mlops2-410712/mnist_test_gcp', '.', '-f', 'trainer.dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops2-410712/mnist_test_gcp']