# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/mlops-group13/train_model@sha256:112cf6bc7028364027f81d1a6a7883fd2484e2cbaac5f238aa0ae0e5b85f3d8f