defaults:
  - override /hydra/sweeper: optuna
  - _self_

# When running "python train_model.py --multirun"
# This grid search will be used 
hydra:
  sweeper:
    n_jobs: 1
    n_trials: 3
    params:
      batch_size: range(8, 24, step=8)

# When running "python train_model.py"
# Then these defaul values will be run
lr: 0.0001
batch_size: 32
max_epochs: 1 #for testing purposes

validation_ratio: 0.15
testing_ratio: 0.10

target_shape:
  - 128
  - 128
